import { useState } from 'react';
import { Bell, Check, LoaderCircle, RefreshCw } from 'lucide-react';
import type { AgentUpdate, Preferences } from '../shared/types';

export function NotificationPreferences({value,onChange}:{value:Preferences['notifications'];onChange:(value:Preferences['notifications'])=>void}) {
  const [message,setMessage]=useState('');
  return <div className="terminal-preferences notification-preferences"><h3>Know when a chat needs you.</h3><p>Harbor can notify you about approvals, questions, errors, and completed work while the app is running.</p>{([['enabled','Enable desktop notifications'],['sound','Play a sound'],['whenFocused','Notify even when Harbor is in front'],['onComplete','Notify when an agent finishes working']] as const).map(([key,label])=><label key={key} className="toggle-field"><input type="checkbox" checked={value[key]} onChange={e=>onChange({...value,[key]:e.target.checked})}/>{label}</label>)}<button className="secondary-button" onClick={async()=>setMessage(await window.harbor.testNotification()?'Test notification sent. If it doesn’t appear, allow Harbor in macOS System Settings → Notifications.':'Desktop notifications aren’t available on this system.')}><Bell size={14}/>Send test notification</button>{message&&<p role="status">{message}</p>}<p className="preferences-note">Status comes from the agents’ own runtime events. Older sessions need to be resumed in Harbor to enable live activity. macOS Focus and notification settings still apply.</p></div>;
}
export function UpdatePreferences() {
  const [updates,setUpdates]=useState<AgentUpdate[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  return <div className="terminal-preferences updates-preferences"><div className="updates-heading"><div><h3>Agents on your machines</h3><p>Check Codex and Claude Code on your saved hosts and project machines.</p></div><button className="secondary-button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{setUpdates(await window.harbor.checkUpdates());}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>{busy?<LoaderCircle className="spin" size={14}/>:<RefreshCw size={14}/>}Check for updates</button></div>{!updates.length&&!busy&&<p className="updates-empty">Run a check to compare installed versions with the latest published releases.</p>}{busy&&<p role="status">Checking machines…</p>}{error&&<p className="form-error" role="alert">{error}</p>}{updates.length>0&&<table className="updates-table"><thead><tr><th>Machine / agent</th><th>Installed</th><th>Latest</th><th>Status</th></tr></thead><tbody>{updates.map((u,index)=><tr key={`${u.hostId}-${u.agent}-${index}`}><td><strong>{u.hostLabel}</strong><small>{u.agent==='codex'?'Codex':'Claude Code'}</small></td><td>{u.installed||'—'}</td><td>{u.latest||'—'}</td><td title={u.error} className={`update-${u.status}`}>{u.status==='available'?'Update available':u.status==='current'?'Up to date':u.status==='missing'?'Not installed':'Unable to check'}{u.error&&<small>{u.error.slice(0,180)}</small>}</td></tr>)}</tbody></table>}<p className="preferences-note">Checks don’t install updates or interrupt running chats. Versions are compared with the agents’ official npm release channels. Preview or pinned channels may differ.</p>{updates[0]&&<small>Last checked {new Date(updates[0].checkedAt).toLocaleString()}</small>}</div>;
}
