import { useState } from 'react';
import { Check, Download, FolderOpen, HardDrive, LoaderCircle, Plus, PanelLeft, Search, Server, Settings2, Terminal, Trash2, X } from 'lucide-react';
import type { Host, Preferences, SavedHost } from '../shared/types';

export function PreferencesDialog({ initial, onClose }: { initial: Preferences; onClose: () => void }) {
  const [draft, setDraft] = useState(() => structuredClone(initial));
  const [tab, setTab] = useState<'hosts' | 'terminal' | 'sidebar'>('hosts');
  const [selected, setSelected] = useState(initial.hosts[0]?.id);
  const [candidates, setCandidates] = useState<Host[] | null>(null);
  const [picked, setPicked] = useState<string[]>([]);
  const [query, setQuery] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [diagnostic, setDiagnostic] = useState('');
  const current = draft.hosts.find(host => host.id === selected);
  const changeHost = (patch: Partial<SavedHost>) => { setDraft(value => ({ ...value, hosts: value.hosts.map(host => host.id === selected ? { ...host, ...patch } : host) })); setDiagnostic(''); };
  const changeConnection = (field: string, value: string | number | undefined) => current && changeHost({ connection: { target: '', ...current.connection, [field]: value } });
  const addManual = () => {
    const host: SavedHost = { id: crypto.randomUUID(), label: 'New host', source: 'manual', enabled: true, defaultDirectory: '~', connection: { target: '' } };
    setDraft(value => ({ ...value, hosts: [...value.hosts, host] })); setSelected(host.id); setCandidates(null); setError('');
  };
  const discover = async () => { setBusy(true); setError(''); try { setCandidates(await window.harbor.sshCandidates()); setPicked([]); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } };
  const importPicked = async () => {
    setBusy(true); setError('');
    try {
      const imported: SavedHost[] = await Promise.all(picked.map(async alias => ({ id: crypto.randomUUID(), label: alias, source: 'ssh-config' as const, enabled: true, defaultDirectory: '~', connection: await window.harbor.resolveSsh(alias) })));
      setDraft(value => ({ ...value, hosts: [...value.hosts, ...imported] })); setSelected(imported[0]?.id); setCandidates(null);
    } catch (err) { setError((err as Error).message); } finally { setBusy(false); }
  };
  const save = async () => { setBusy(true); setError(''); try { await window.harbor.savePreferences(draft); onClose(); } catch (err) { setError((err as Error).message.replace(/^Error invoking remote method '[^']+': Error: /, '')); } finally { setBusy(false); } };
  return <div className="modal-backdrop"><section className="modal preferences-modal" role="dialog" aria-modal="true" aria-labelledby="preferences-title">
    <div className="modal-heading"><h2 id="preferences-title">Preferences</h2><button className="icon-button" aria-label="Close preferences" onClick={onClose} disabled={busy}><X size={18} /></button></div>
    <div className="preferences-tabs"><button className={tab === 'hosts' ? 'active' : ''} onClick={() => setTab('hosts')}><Server size={15} />Hosts</button><button className={tab === 'terminal' ? 'active' : ''} onClick={() => setTab('terminal')}><Terminal size={15} />Terminal</button><button className={tab === 'sidebar' ? 'active' : ''} onClick={() => setTab('sidebar')}><PanelLeft size={15} />Sidebar</button></div>
    {tab === 'hosts' ? <>
      <div className="preferences-intro"><p>Choose the machines available when you launch a session.</p><div><button className="secondary-button" onClick={() => void discover()} disabled={busy}><Download size={14} />Import from SSH config</button><button className="secondary-button" onClick={addManual} disabled={busy}><Plus size={14} />Add manually</button></div></div>
      {candidates ? <div className="ssh-import"><div className="import-heading"><h3>Select aliases to import</h3><button className="text-button" onClick={() => setCandidates(null)}>Back to hosts</button></div><div className="search-box"><Search size={14} /><input aria-label="Search SSH aliases" placeholder="Search aliases…" value={query} onChange={event => setQuery(event.target.value)} /></div><div className="import-options">{candidates.filter(host => host.label.toLowerCase().includes(query.toLowerCase())).map(host => {
        const added = draft.hosts.some(saved => saved.connection?.target === host.id);
        return <label key={host.id} className="import-option"><input type="checkbox" checked={added || picked.includes(host.id)} disabled={added || busy} onChange={event => setPicked(values => event.target.checked ? [...values, host.id] : values.filter(id => id !== host.id))} /><span>{host.label}</span>{added && <small>Already added</small>}</label>;
      })}{!candidates.length && <p>No literal Host aliases were found in ~/.ssh/config. You can add a host manually.</p>}</div><div className="import-footer"><small>Only selected aliases are imported. Your SSH config is never edited.</small><button className="primary-button" disabled={!picked.length || busy} onClick={() => void importPicked()}>{busy ? <LoaderCircle className="spin" size={14} /> : <Download size={14} />}Import selected ({picked.length})</button></div></div> : <div className="host-preferences-grid">
        <div className="saved-host-list">{draft.hosts.map(host => <button key={host.id} className={selected === host.id ? 'active' : ''} onClick={() => { setSelected(host.id); setDiagnostic(''); }}>{host.id === 'local' ? <HardDrive size={17} /> : <Server size={17} />}<span><strong>{host.label}</strong><small>{host.enabled ? host.connection?.target || 'Local machine' : 'Hidden from launcher'}</small></span><span className={`status-dot ${host.enabled ? 'running' : 'missing'}`} /></button>)}</div>
        {current && <div className="host-editor" key={current.id}>
          <div className="host-editor-heading"><span className="eyebrow">{current.source === 'ssh-config' ? 'IMPORTED FROM SSH CONFIG' : current.source === 'local' ? 'LOCAL MACHINE' : 'MANUAL CONNECTION'}</span><label className="toggle-field"><input type="checkbox" aria-label="Show in launcher" checked={current.enabled} onChange={event => changeHost({ enabled: event.target.checked })} />Show in launcher</label></div>
          <label>Display name<input value={current.label} maxLength={100} onChange={event => changeHost({ label: event.target.value })} /></label>
          {current.id !== 'local' && <><label>SSH alias or address<input aria-label="SSH alias or address" value={current.connection?.target || ''} placeholder="devbox or user@example.com" onChange={event => changeConnection('target', event.target.value)} /><small>Uses this target’s SSH config, including jump hosts and authentication.</small></label><label>Hostname override<input value={current.connection?.hostname || ''} placeholder="Use SSH config" onChange={event => changeConnection('hostname', event.target.value || undefined)} /></label><div className="form-row"><label>Username<input value={current.connection?.user || ''} placeholder="Use SSH config" onChange={event => changeConnection('user', event.target.value || undefined)} /></label><label>Port<input type="number" min="1" max="65535" value={current.connection?.port ?? ''} placeholder="Use SSH config" onChange={event => changeConnection('port', event.target.value ? Number(event.target.value) : undefined)} /></label></div><label>Identity file<input value={current.connection?.identityFile || ''} placeholder="Use SSH config / SSH agent" onChange={event => changeConnection('identityFile', event.target.value || undefined)} /><small>Path on this Mac, for example ~/.ssh/id_ed25519.</small></label></>}
          <label>Default working directory<input value={current.defaultDirectory} onChange={event => changeHost({ defaultDirectory: event.target.value })} /></label>
          <div className="host-editor-actions"><button className="text-button" disabled={busy} onClick={async () => { setBusy(true); setDiagnostic(''); try { const result = await window.harbor.diagnose(current.connection ?? 'local'); setDiagnostic(result.ok ? `Connected · ${result.tmux} · Codex ${result.codex ? 'available' : 'not found'} · Claude Code ${result.claude ? 'available' : 'not found'}` : result.error || 'Connection failed.'); } catch (err) { setDiagnostic((err as Error).message); } finally { setBusy(false); } }}><Check size={14} />Test connection</button>{current.id !== 'local' && <button className="text-button danger" onClick={() => { setDraft(value => ({ ...value, hosts: value.hosts.filter(host => host.id !== current.id) })); setSelected('local'); }}><Trash2 size={14} />Remove host</button>}</div>{diagnostic && <div className="diagnostic" role="status">{diagnostic}</div>}
        </div>}
      </div>}
      <p className="preferences-note">Changes apply to new sessions. Hiding or removing a host keeps its existing sessions and their connection settings intact.</p>
    </> : tab === 'sidebar' ? <div className="terminal-preferences sidebar-preferences"><h3>A little more room.</h3><p>Collapse or pin the sidebar with its toggle, or press ⌘ B. Harbor remembers your choice.</p><label className="toggle-field"><input type="checkbox" checked={draft.sidebar.expandOnHover} onChange={event => setDraft(value => ({ ...value, sidebar: { expandOnHover: event.target.checked } }))} />Expand sidebar on hover</label><p className="preferences-note">When collapsed, hover over the icon rail to reveal your sessions. Move back to the terminal to tuck it away. The terminal stays the same size while you peek.</p></div> : <div className="terminal-preferences"><h3>Make room for your work.</h3><p>These preferences update open terminals as soon as you save.</p><div className="form-row"><label>Font size<input type="number" min="9" max="28" value={draft.terminal.fontSize} onChange={event => setDraft(value => ({ ...value, terminal: { ...value.terminal, fontSize: Number(event.target.value) } }))} /></label><label>Cursor<select value={draft.terminal.cursorBlink ? 'blink' : 'steady'} onChange={event => setDraft(value => ({ ...value, terminal: { ...value.terminal, cursorBlink: event.target.value === 'blink' } }))}><option value="blink">Blinking</option><option value="steady">Steady</option></select></label></div><label>Font family<input value={draft.terminal.fontFamily} onChange={event => setDraft(value => ({ ...value, terminal: { ...value.terminal, fontFamily: event.target.value } }))} /><small>Use an installed monospace font. Comma-separated fallback fonts are supported.</small></label><div className="font-preview" style={{ fontFamily: draft.terminal.fontFamily, fontSize: draft.terminal.fontSize }}><span>❯</span> echo "Hello, Harbor"<br /><span className="preview-blue">Blue</span> <span className="preview-green">Green</span> <span className="preview-orange">Amber</span> <span className="preview-purple">Purple</span></div><p className="preferences-note">Full ANSI and true color are enabled. Newly launched sessions ignore inherited color-disabling variables. Existing processes keep their original environment.</p><button className="text-button" onClick={() => void window.harbor.openDataDir()}><FolderOpen size={14} />Open preferences folder</button></div>}
    {error && <div className="form-error" role="alert">{error}</div>}<div className="modal-footer"><button className="secondary-button" onClick={onClose} disabled={busy}>Cancel</button><button className="primary-button" onClick={() => void save()} disabled={busy || candidates !== null}>{busy ? <LoaderCircle className="spin" size={14} /> : <Check size={14} />}Save preferences</button></div>
  </section></div>;
}
