import { useState } from 'react';
import { Check, Code2, FolderOpen, LoaderCircle, Plus, Sparkles, Terminal, X } from 'lucide-react';
import type { Launcher, Project, Session, Snapshot } from '../shared/types';

export function ProjectDialog({snapshot,onClose,onCreated,onPreferences}:{snapshot:Snapshot;onClose:()=>void;onCreated:(p:Project)=>void;onPreferences:()=>void}) {
  const [host,setHost]=useState(snapshot.hosts[0]?.id||'');const [cwd,setCwd]=useState(snapshot.hosts[0]?.defaultDirectory||'~');const [name,setName]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  return <div className="modal-backdrop"><form className="modal project-modal" role="dialog" aria-modal="true" aria-label="Add project" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{onCreated(await window.harbor.addProject({name,host,cwd}));}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><div className="modal-heading"><h2>Add project</h2><button type="button" className="icon-button" aria-label="Close dialog" disabled={busy} onClick={onClose}><X size={18}/></button></div><p>A project is a directory on your Mac or a saved SSH host. Its existing Codex and Claude chats will appear automatically.</p><label>Host<select value={host} onChange={e=>{if(e.target.value==='manage'){onPreferences();return;}setHost(e.target.value);setCwd(snapshot.hosts.find(h=>h.id===e.target.value)?.defaultDirectory||'~');}}>{snapshot.hosts.map(h=><option key={h.id} value={h.id}>{h.label}</option>)}<option value="manage">Manage hosts in Preferences…</option></select></label><label>Project directory<div className="input-action"><input required value={cwd} onChange={e=>setCwd(e.target.value)}/>{host==='local'&&<button type="button" aria-label="Choose project folder" onClick={async()=>{const folder=await window.harbor.chooseFolder();if(folder)setCwd(folder);}}><FolderOpen size={17}/></button>}</div></label><label>Project name<input value={name} maxLength={100} placeholder="Defaults to the directory name" onChange={e=>setName(e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" className="secondary-button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy||!host}>{busy?<LoaderCircle size={15} className="spin"/>:<Plus size={15}/>}Add project</button></div></form></div>;
}
export function ChatDialog({project,onClose,onCreated}:{project:Project;onClose:()=>void;onCreated:(s:Session)=>void}) {
  const [launcher,setLauncher]=useState<Launcher>('codex');const [name,setName]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  return <div className="modal-backdrop"><form className="modal chat-modal" role="dialog" aria-modal="true" aria-label="New chat" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{onCreated(await window.harbor.create({name:name.trim()||(launcher==='shell'?'New terminal':'New chat'),host:project.hostId||'local',cwd:project.cwd,projectId:project.id,launcher}));}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><div className="modal-heading"><h2>New chat</h2><button type="button" className="icon-button" disabled={busy} aria-label="Close dialog" onClick={onClose}><X size={18}/></button></div><p className="chat-project-label">{project.name}<small>{project.hostLabel} · {project.cwd}</small></p><div className="launcher-options">{(['codex','claude','shell'] as const).map(kind=><button type="button" key={kind} className={launcher===kind?'selected':''} onClick={()=>setLauncher(kind)}>{kind==='codex'?<Code2 size={21}/>:kind==='claude'?<Sparkles size={21}/>:<Terminal size={21}/>}<span>{kind==='codex'?'Codex':kind==='claude'?'Claude Code':'Terminal'}</span>{launcher===kind&&<Check size={13}/>}</button>)}</div><label>Chat name<input value={name} maxLength={100} placeholder={launcher==='shell'?'Optional terminal name':'Automatically named by the agent'} onChange={e=>setName(e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" className="secondary-button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy}>{busy?<LoaderCircle size={15} className="spin"/>:<Plus size={15}/>}Create chat</button></div></form></div>;
}
export function RenameDialog({initial,kind,onClose,onSave}:{initial:string;kind:'chat'|'project';onClose:()=>void;onSave:(name:string)=>Promise<void>}){
 const [name,setName]=useState(initial);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 return <div className="modal-backdrop"><form className="modal rename-modal" role="dialog" aria-modal="true" aria-label={`Rename ${kind}`} onSubmit={async e=>{e.preventDefault();setBusy(true);try{await onSave(name);}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><div className="modal-heading"><h2>Rename {kind}</h2><button type="button" className="icon-button" aria-label="Close dialog" disabled={busy} onClick={onClose}><X size={18}/></button></div><label>Name<input value={name} required maxLength={100} onChange={e=>setName(e.target.value)}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<div className="modal-footer"><button type="button" className="secondary-button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy}>Save name</button></div></form></div>;
}
