import { DirectoryPicker } from './DirectoryPicker';
import { AgentIcon } from './AgentIcon';
import { agentModes } from '../shared/agentModes';
import { useState } from 'react';
import { Check, LoaderCircle, Plus, X } from 'lucide-react';
import type { Launcher, Project, Session, Snapshot, Preferences } from '../shared/types';

export function ProjectDialog({snapshot,onClose,onCreated,onPreferences}:{snapshot:Snapshot;onClose:()=>void;onCreated:(p:Project)=>void;onPreferences:()=>void}) {
  const [host,setHost]=useState(snapshot.hosts[0]?.id||'');const [cwd,setCwd]=useState(snapshot.hosts[0]?.defaultDirectory||'~');const [name,setName]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  return <div className="modal-backdrop"><form className="modal project-modal" role="dialog" aria-modal="true" aria-label="Add project" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{onCreated(await window.harbor.addProject({name,host,cwd}));}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><div className="modal-heading"><h2>Add project</h2><button type="button" className="icon-button" aria-label="Close dialog" disabled={busy} onClick={onClose}><X size={18}/></button></div><p>A project is a directory on your Mac or a saved SSH host. Its existing Codex and Claude chats will appear automatically.</p><label>Host<select aria-label="Host" disabled={busy} value={host} onChange={e=>{if(e.target.value==='manage'){onPreferences();return;}setHost(e.target.value);setCwd(snapshot.hosts.find(h=>h.id===e.target.value)?.defaultDirectory||'~');}}>{snapshot.hosts.map(h=><option key={h.id} value={h.id}>{h.label}</option>)}<option value="manage">Manage hosts in Preferences…</option></select></label><DirectoryPicker key={host} host={host} hostLabel={snapshot.hosts.find(h=>h.id===host)?.label||'Host'} local={!snapshot.hosts.find(h=>h.id===host)?.connection} value={cwd} onChange={setCwd} disabled={busy}/><label>Project name<input value={name} maxLength={100} placeholder="Defaults to the directory name" onChange={e=>setName(e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" className="secondary-button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy||!host}>{busy?<LoaderCircle size={15} className="spin"/>:<Plus size={15}/>}Add project</button></div></form></div>;
}
export function ChatDialog({project,defaults,onClose,onCreated}:{project:Project;defaults:Preferences['agents'];onClose:()=>void;onCreated:(s:Session)=>void}) {
  const [launcher,setLauncher]=useState<Launcher>('codex');const [modes,setModes]=useState({...defaults});const [name,setName]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  return <div className="modal-backdrop"><form className="modal chat-modal" role="dialog" aria-modal="true" aria-label="New chat" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{onCreated(await window.harbor.create({name:name.trim()||(launcher==='shell'?'New terminal':'New chat'),host:project.hostId||'local',cwd:project.cwd,projectId:project.id,launcher,...(launcher==='codex'||launcher==='claude'?{permissionMode:modes[launcher]}:{})}));}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><div className="modal-heading"><h2>New chat</h2><button type="button" className="icon-button" disabled={busy} aria-label="Close dialog" onClick={onClose}><X size={18}/></button></div><p className="chat-project-label">{project.name}<small>{project.hostLabel} · {project.cwd}</small></p><div className="launcher-options">{(['codex','claude','shell'] as const).map(kind=><button type="button" key={kind} className={launcher===kind?'selected':''} onClick={()=>setLauncher(kind)}><AgentIcon launcher={kind} size={21}/><span>{kind==='codex'?'Codex':kind==='claude'?'Claude Code':'Terminal'}</span>{launcher===kind&&<Check size={13}/>}</button>)}</div>{(launcher==='codex'||launcher==='claude')&&<label>Permission mode<select aria-label="Permission mode" value={modes[launcher]} onChange={e=>setModes(v=>({...v,[launcher]:e.target.value}))}>{agentModes[launcher].map(mode=><option key={mode.value} value={mode.value}>{mode.label}</option>)}</select><small>{agentModes[launcher].find(mode=>mode.value===modes[launcher])?.description}</small></label>}<label>Chat name<input value={name} maxLength={100} placeholder={launcher==='shell'?'Optional terminal name':'Automatically named by the agent'} onChange={e=>setName(e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" className="secondary-button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy}>{busy?<LoaderCircle size={15} className="spin"/>:<Plus size={15}/>}Create chat</button></div></form></div>;
}
export function RenameDialog({initial,kind,onClose,onSave}:{initial:string;kind:'chat'|'project';onClose:()=>void;onSave:(name:string)=>Promise<void>}){
 const [name,setName]=useState(initial);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 return <div className="modal-backdrop"><form className="modal rename-modal" role="dialog" aria-modal="true" aria-label={`Rename ${kind}`} onSubmit={async e=>{e.preventDefault();setBusy(true);try{await onSave(name);}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><div className="modal-heading"><h2>Rename {kind}</h2><button type="button" className="icon-button" aria-label="Close dialog" disabled={busy} onClick={onClose}><X size={18}/></button></div><label>Name<input value={name} required maxLength={100} onChange={e=>setName(e.target.value)}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<div className="modal-footer"><button type="button" className="secondary-button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy}>Save name</button></div></form></div>;
}
