import { DirectoryPicker } from './DirectoryPicker';
import { AgentIcon } from './AgentIcon';
import { agentModes } from '../shared/agentModes';
import { useState, type RefObject } from 'react';
import { Check, LoaderCircle, Plus, Trash2, X } from 'lucide-react';
import type { Launcher, Project, Session, Snapshot, Preferences } from '../shared/types';

export function ProjectDialog({snapshot,onClose,onCreated,onPreferences}:{snapshot:Snapshot;onClose:()=>void;onCreated:(p:Project)=>void;onPreferences:()=>void}) {
  const [host,setHost]=useState(snapshot.hosts[0]?.id||'');const [cwd,setCwd]=useState(snapshot.hosts[0]?.defaultDirectory||'~');const [name,setName]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  return <div className="modal-backdrop"><form className="modal project-modal" role="dialog" aria-modal="true" aria-label="Add project" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{onCreated(await window.harbor.addProject({name,host,cwd}));}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><div className="modal-heading"><h2>Add project</h2><button type="button" className="icon-button" aria-label="Close dialog" disabled={busy} onClick={onClose}><X size={18}/></button></div><p>A project is a directory on your Mac or a saved SSH host. Its existing Codex and Claude chats will appear automatically.</p><label>Host<select aria-label="Host" disabled={busy} value={host} onChange={e=>{if(e.target.value==='manage'){onPreferences();return;}setHost(e.target.value);setCwd(snapshot.hosts.find(h=>h.id===e.target.value)?.defaultDirectory||'~');}}>{snapshot.hosts.map(h=><option key={h.id} value={h.id}>{h.label}</option>)}<option value="manage">Manage remotes in Settings…</option></select></label><DirectoryPicker key={host} host={host} hostLabel={snapshot.hosts.find(h=>h.id===host)?.label||'Host'} local={!snapshot.hosts.find(h=>h.id===host)?.connection} value={cwd} onChange={setCwd} disabled={busy}/><label>Project name<input value={name} maxLength={100} placeholder="Defaults to the directory name" onChange={e=>setName(e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" className="secondary-button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy||!host}>{busy?<LoaderCircle size={15} className="spin"/>:<Plus size={15}/>}Add project</button></div></form></div>;
}
const chatLaunchers=['codex','claude','shell'] as const;
export function ChatDialog({project,defaults,shortcut,onClose,onCreated}:{project:Project;defaults:Preferences['agents'];shortcut:RefObject<(index:number)=>void>;onClose:()=>void;onCreated:(s:Session)=>void}) {
  const [launcher,setLauncher]=useState<Launcher>('codex');const [modes,setModes]=useState({...defaults});const [name,setName]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  shortcut.current=index=>{const kind=chatLaunchers[index-1];if(kind&&!busy)setLauncher(kind);};
  return <div className="modal-backdrop"><form className="modal chat-modal" role="dialog" aria-modal="true" aria-label="New chat" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{onCreated(await window.harbor.create({name:name.trim()||(launcher==='shell'?'New terminal':'New chat'),host:project.hostId||'local',cwd:project.cwd,projectId:project.id,launcher,...(launcher==='codex'||launcher==='claude'?{permissionMode:modes[launcher]}:{})}));}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><div className="modal-heading"><h2>New chat</h2><button type="button" className="icon-button" disabled={busy} aria-label="Close dialog" onClick={onClose}><X size={18}/></button></div><p className="chat-project-label">{project.name}<small>{project.hostLabel} · {project.cwd}</small></p><div className="launcher-options">{chatLaunchers.map((kind,index)=><button type="button" key={kind} className={launcher===kind?'selected':''} aria-pressed={launcher===kind} aria-keyshortcuts={`Meta+${index+1}`} title={`Select with ⌘${index+1}`} onClick={()=>setLauncher(kind)}><AgentIcon launcher={kind} size={21}/><span>{kind==='codex'?'Codex':kind==='claude'?'Claude Code':'Terminal'}</span><kbd aria-hidden="true">⌘{index+1}</kbd>{launcher===kind&&<Check size={13}/>}</button>)}</div>{(launcher==='codex'||launcher==='claude')&&<label>Permission mode<select aria-label="Permission mode" value={modes[launcher]} onChange={e=>setModes(v=>({...v,[launcher]:e.target.value}))}>{agentModes[launcher].map(mode=><option key={mode.value} value={mode.value}>{mode.label}</option>)}</select><small>{agentModes[launcher].find(mode=>mode.value===modes[launcher])?.description}</small></label>}<label>Chat name<input value={name} maxLength={100} placeholder={launcher==='shell'?'Optional terminal name':'Automatically named by the agent'} onChange={e=>setName(e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" className="secondary-button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy}>{busy?<LoaderCircle size={15} className="spin"/>:<Plus size={15}/>}Create chat</button></div></form></div>;
}
export function RenameDialog({initial,kind,onClose,onSave}:{initial:string;kind:'chat'|'project';onClose:()=>void;onSave:(name:string)=>Promise<void>}){
 const [name,setName]=useState(initial);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 return <div className="modal-backdrop"><form className="modal rename-modal" role="dialog" aria-modal="true" aria-label={`Rename ${kind}`} onSubmit={async e=>{e.preventDefault();setBusy(true);try{await onSave(name);}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><div className="modal-heading"><h2>Rename {kind}</h2><button type="button" className="icon-button" aria-label="Close dialog" disabled={busy} onClick={onClose}><X size={18}/></button></div><label>Name<input value={name} required maxLength={100} onChange={e=>setName(e.target.value)}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<div className="modal-footer"><button type="button" className="secondary-button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy}>Save name</button></div></form></div>;
}
// Deleting a project only removes Harbor's entry for it. Running chats are named so nothing keeps running unseen by surprise; hiding is offered as the reversible option.
export function DeleteProjectDialog({project,running,onClose,onHide,onDelete}:{project:Project;running:Session[];onClose:()=>void;onHide:()=>Promise<void>;onDelete:()=>Promise<void>}){
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const act=async(action:()=>Promise<void>)=>{setBusy(true);setError('');try{await action();}catch(err){setError((err as Error).message.replace(/^Error invoking remote method '[^']+': Error: /,''));setBusy(false);}};
 return <div className="modal-backdrop"><form className="modal delete-project-modal" role="alertdialog" aria-modal="true" aria-label={`Delete project ${project.name}`} onSubmit={e=>{e.preventDefault();void act(onDelete);}}>
  <div className="modal-heading"><h2>Delete “{project.name}”?</h2><button type="button" className="icon-button" aria-label="Close dialog" disabled={busy} onClick={onClose}><X size={18}/></button></div>
  <p>This removes the project from Harbor's sidebar. Only Harbor's project entry is deleted:</p>
  <ul className="delete-project-facts">
   <li>The folder <code>{project.hostLabel} · {project.cwd}</code> and its files are not touched.</li>
   <li>Saved Codex and Claude conversations are kept. Add the folder as a project again to bring them back.</li>
   {running.length?<li className="attention-text">{running.length} running {running.length===1?'chat keeps':'chats keep'} running in tmux: {running.map(s=>s.name).join(', ')}. Open tabs stay open, but these chats leave the sidebar. Close them first if you want to stop them.</li>:<li>No chats in this project are running, and no tmux session is closed.</li>}
  </ul>
  <p className="delete-project-hint">To just get it out of the way, hide it instead. Hidden projects come back from the sidebar or Settings → Projects.</p>
  {error&&<p role="alert" className="form-error">{error}</p>}
  <div className="modal-footer"><button type="button" className="secondary-button" disabled={busy} onClick={onClose}>Cancel</button><button type="button" className="secondary-button" disabled={busy} onClick={()=>void act(onHide)}>Hide instead</button><button className="primary-button danger-button" disabled={busy}>{busy?<LoaderCircle size={15} className="spin"/>:<Trash2 size={15}/>}Delete project</button></div>
 </form></div>;
}
