import { useState } from 'react';
import { ArrowDown, ArrowUp, GripVertical, Trash2 } from 'lucide-react';
import type { Project } from '../shared/types';
import { moveItem } from '../shared/dropCue';
import { useListReorder } from './useDropCue';
/** Settings → Projects. Every change applies right away; deleting asks for confirmation first. */
export function ProjectManager({projects,onChange}:{projects:Project[];onChange:(projects:Project[])=>void}) {
  const [confirm,setConfirm]=useState<string>();
  const move=(id:string,target:string,after:boolean)=>{const ids=moveItem(projects.map(p=>p.id),id,target,after);if(ids)onChange(ids.map(id=>projects.find(p=>p.id===id)!));};
  const drag=useListReorder('application/x-harbor-project',projects.map(p=>p.id),move);
  return <div className="project-manager"><p>Drag to reorder projects. Hidden projects stay listed here. Deleting a project removes it from Harbor; its files, saved conversations, and running chats are kept.</p>{projects.map((project,index)=>confirm===project.id?<div className="managed-project confirm-delete" key={project.id} role="group" aria-label={`Delete ${project.name}`}><Trash2 size={16}/><div><strong>Delete {project.name} from Harbor?</strong><small>Its files, saved conversations, and running chats are kept.</small></div><button className="secondary-button" onClick={()=>setConfirm(undefined)}>Cancel</button><button className="secondary-button danger" onClick={()=>{setConfirm(undefined);onChange(projects.filter(p=>p.id!==project.id));}}>Delete project</button></div>:<div className={`managed-project ${drag.className(project.id)}`} key={project.id} {...drag.source(project.id)} {...drag.target(project.id)}><GripVertical size={16}/><div><strong>{project.name}</strong><small>{project.hostLabel} · {project.cwd}</small></div><button className="icon-button" aria-label={`Move ${project.name} up`} disabled={!index} onClick={()=>move(project.id,projects[index-1].id,false)}><ArrowUp size={15}/></button><button className="icon-button" aria-label={`Move ${project.name} down`} disabled={index===projects.length-1} onClick={()=>move(project.id,projects[index+1].id,true)}><ArrowDown size={15}/></button><label className="toggle-field"><input type="checkbox" checked={!project.hidden} onChange={event=>onChange(projects.map(p=>p.id===project.id?{...p,hidden:!event.target.checked}:p))}/>Visible</label><button className="icon-button danger" aria-label={`Delete project ${project.name}`} onClick={()=>setConfirm(project.id)}><Trash2 size={16}/></button></div>)}{!projects.length&&<p>No projects. Add one from the sidebar.</p>}</div>;
}
