import { ArrowDown, ArrowUp, GripVertical, Trash2 } from 'lucide-react';
import type { Project } from '../shared/types';
import { moveItem } from '../shared/dropCue';
import { useListReorder } from './useDropCue';
export function ProjectManager({projects,onChange}:{projects:Project[];onChange:(projects:Project[])=>void}) {
  const move=(id:string,target:string,after:boolean)=>{const ids=moveItem(projects.map(p=>p.id),id,target,after);if(ids)onChange(ids.map(id=>projects.find(p=>p.id===id)!));};
  const drag=useListReorder('application/x-harbor-project',projects.map(p=>p.id),move);
  return <div className="project-manager"><h3>Projects</h3><p>Drag to reorder projects. Hidden projects stay available here. Deleting a project removes it from Harbor; its files, saved conversations, and running sessions are kept. Changes apply when you save.</p>{projects.map((project,index)=><div className={`managed-project ${drag.className(project.id)}`} key={project.id} {...drag.source(project.id)} {...drag.target(project.id)}><GripVertical size={16}/><div><strong>{project.name}</strong><small>{project.hostLabel} · {project.cwd}</small></div><button className="icon-button" aria-label={`Move ${project.name} up`} disabled={!index} onClick={()=>move(project.id,projects[index-1].id,false)}><ArrowUp size={15}/></button><button className="icon-button" aria-label={`Move ${project.name} down`} disabled={index===projects.length-1} onClick={()=>move(project.id,projects[index+1].id,true)}><ArrowDown size={15}/></button><label className="toggle-field"><input type="checkbox" checked={!project.hidden} onChange={event=>onChange(projects.map(p=>p.id===project.id?{...p,hidden:!event.target.checked}:p))}/>Visible</label><button className="icon-button danger" aria-label={`Delete project ${project.name}`} onClick={()=>onChange(projects.filter(p=>p.id!==project.id))}><Trash2 size={16}/></button></div>)}{!projects.length&&<p>No projects. Add one from the sidebar.</p>}</div>;
}
